-- ============================================
-- AI CHATBOT RPC SUPPORT
-- ============================================

-- Function to execute read-only SQL generated by AI
-- SECURITY DEFINER allows it to run with elevated privileges, 
-- but we should be EXTREMELY careful.
CREATE OR REPLACE FUNCTION public.execute_ai_query(sql_query TEXT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    result JSONB;
BEGIN
    -- Basic protection: only allow SELECT statements
    IF NOT (sql_query ILIKE 'SELECT%') THEN
        RAISE EXCEPTION 'Only SELECT statements are allowed.';
    END IF;

    -- Basic protection: disallow multiple statements
    IF sql_query ~ ';' AND sql_query !~ ';$' THEN
        RAISE EXCEPTION 'Multiple statements are not allowed.';
    END IF;

    -- Execute the query and convert to JSONB
    EXECUTE 'SELECT jsonb_agg(t) FROM (' || sql_query || ') t' INTO result;
    
    RETURN COALESCE(result, '[]'::jsonb);
EXCEPTION WHEN OTHERS THEN
    RAISE EXCEPTION 'SQL Execution Error: %', SQLERRM;
END;
$$;

-- Grant access to authenticated users
GRANT EXECUTE ON FUNCTION public.execute_ai_query(TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.execute_ai_query(TEXT) TO service_role;
